// Generated by CoffeeScript 1.4.0
(function() {

  window.dome = function(htmlString, option) {
    var wrapper;
    if (option == null) {
      option = 'single';
    }
    if (option === 'single') {
      wrapper = document.createElement('div');
    } else {
      wrapper = document.createElement(option);
    }
    wrapper.innerHTML = htmlString;
    if (wrapper.childNodes.length === 1 && option === 'single') {
      return wrapper.childNodes[0];
    }
    return wrapper;
  };

}).call(this);
